#!/bin/sh

# Something about python3 -m unittest discover overrides the
# environment settings at the beginning of test_billtracker.py,
# resulting in overwriting the REAL database set in your
# environment's DATABASE_URL.
# Don't risk it; run this instead:

python3 -m unittest \
    test.test_billtracker \
    test.test_nmlegisbill \
    test.test_accdb
