#!/bin/sh

# Need to run all the tests separately
pytest --quiet --tb=native  tests/test_accdb.py && \
pytest --quiet --tb=native tests/test_nmlegisbill.py && \
pytest --quiet --tb=native tests/test_billtracker.py
