"""Legislators: add party and county.

Revision ID: 828c0b9faad4
Revises: a2d704c13d1e
Create Date: 2023-04-08 15:28:11.615847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828c0b9faad4'
down_revision = 'a2d704c13d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legislator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=15), nullable=True))
        batch_op.drop_column('home_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legislator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_phone', sa.VARCHAR(length=25), nullable=True))
        batch_op.drop_column('county')
        batch_op.drop_column('party')

    # ### end Alembic commands ###
