"""Initial db

Revision ID: 0f7ea1f797a1
Revises: 
Create Date: 2019-01-13 21:33:51.825003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7ea1f797a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billno', sa.String(length=20), nullable=True),
    sa.Column('mod_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('last_action_date', sa.DateTime(), nullable=True),
    sa.Column('chamber', sa.String(length=2), nullable=True),
    sa.Column('billtype', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('statusHTML', sa.String(length=500), nullable=True),
    sa.Column('statustext', sa.String(length=500), nullable=True),
    sa.Column('sponsor', sa.String(length=20), nullable=True),
    sa.Column('sponsorlink', sa.String(length=150), nullable=True),
    sa.Column('curloc', sa.String(length=20), nullable=True),
    sa.Column('curloclink', sa.String(length=150), nullable=True),
    sa.Column('FIRlink', sa.String(length=150), nullable=True),
    sa.Column('LESClink', sa.String(length=150), nullable=True),
    sa.Column('amendlink', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('auth_code', sa.String(length=20), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('userbills',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbills')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('bill')
    # ### end Alembic commands ###
