"""bill contentslink

Revision ID: 3b44ded5afb3
Revises: be1be46262a6
Create Date: 2019-01-28 14:06:49.873099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b44ded5afb3'
down_revision = 'be1be46262a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contentslink', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('contentslink')

    # ### end Alembic commands ###
