"""Add LegSessions table

Revision ID: 60f58c090263
Revises: f34de039b188
Create Date: 2020-12-24 16:42:37.643618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f58c090263'
down_revision = 'f34de039b188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leg_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yearcode', sa.String(length=8), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('typename', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leg_session')
    # ### end Alembic commands ###
