"""empty message

Revision ID: 63aa2c23b30c
Revises: 60f58c090263
Create Date: 2022-12-16 10:51:36.880405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63aa2c23b30c'
down_revision = '60f58c090263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('yearcode', sa.String(), nullable=True),
    sa.Column('bills', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('editors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_lists', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('interest_lists')

    op.drop_table('interest_list')
    # ### end Alembic commands ###
