"""empty message

Revision ID: 657ce93b2db0
Revises: 0f7ea1f797a1
Create Date: 2019-01-16 12:39:44.739685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657ce93b2db0'
down_revision = '0f7ea1f797a1'
branch_labels = None
depends_on = None

#
# This migration has commented-out lines relating to 'create_date'.
# This is a field left over from a bogus migration that I didn't save.
# If downgrading from this version, there's no reason to put back
# create_date since no code ever referenced it and it's not in the
# original migration: hence, commented out.
#

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('bill', 'create_date')
    # with op.batch_alter_table('bill') as batch_op:
    #     batch_op.drop_column('create_date')
    op.add_column('user', sa.Column('bills_seen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'bills_seen')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('bills_seen')
    # op.add_column('bill', sa.Column('create_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
